### PR TITLE
ci: add migration files to release archive

### LINKED ISSUE #343: Add migrations test files to artifacts
When resetting dev nets the migrations config files are presently out of sync unless we manually update the pipeline repos with the new migrations. These exist inside the many-rs repo test suite but are not part of the artifacts. If we add these to artifact generation for both CircleCI PR builds and Github releases, we can improve our automation by including the most up-to-date migrations configs with all enabled at block 0 for testing. 

- [ ] Add the abci, ledger and kvstore (future) migrations config files to CircleCI and Github release artifact .gz files

**Describe alternatives you've considered**
Considered pulling directly from many-rs repo main branch, but this will not always guarantee parity with release build reqs.

### PR DESCRIPTION
**Pull request by fmorency**
Fixes #343

### CODE REVIEW

**Comment by hansl** [comment]
My only major question would be why we don't auto-generate the migration file using the command line.

**Comment by fmorency** [comment]
> My only major question would be why we don't auto-generate the migration file using the command line.

That's a good idea! If you don't mind, let's create another issue/PR for that and unblock @jgryffindor with this PR.

**Comment by fmorency** [comment]
#350

**Review by hansl — APPROVED** [review]

**Review by jgryffindor — APPROVED** [review]
Looks good!

**Pull request merged**
